name: gg_router_example
description: A GgRouter Demonstrator.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0<4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.4
  gg_router:
    path: ../
  gg_value: ^1.0.3-dev.1
  gg_map_animation: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  gg_easy_widget_test: ^1.0.0

flutter:
  uses-material-design: true
