name: Dart Script Execution

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git user
        run: |
          git config --global user.email "githubaction@inlavigo.com"
          git config --global user.name "Github Action"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Flutter Project
        run: |
          if ([ -f pubspec.yaml ] && grep -q "sdk: flutter" pubspec.yaml) || ([ -f .github/workflows/sdk ] && grep -q "flutter" .github/workflows/sdk); then
            echo "is_flutter=true" >> "$GITHUB_ENV"
          else
            echo "is_flutter=false" >> "$GITHUB_ENV"
          fi

      # - name: Cache Flutter Dependencies
      #   if: env.is_flutter == 'true'
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.pub-cache
      #       **/pubspec.lock
      #     key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-flutter-
      #
      # - name: Cache Dart Dependencies
      #   if: env.is_flutter == 'false'
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.pub-cache
      #       **/pubspec.lock
      #     key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-dart-

      - name: Set up Flutter
        if: env.is_flutter == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Set up Dart SDK
        if: env.is_flutter == 'false'
        uses: dart-lang/setup-dart@v1.6.2
        with:
          sdk: "stable"

      - name: Install dependencies
        run: |
          if [ ${{ env.is_flutter }} == 'true' ]; then
            flutter pub get
          else
            dart pub get
          fi

      - name: Install the gg developer command line
        run: dart pub global activate gg

      - name: What was changed in the last commit?
        run: |
          gg info last-changes-hash
          gg info modified-files --force

      - name: Did you execute »gg do commit«?
        run: gg did commit

      - name: Did you execute »gg do push«?
        run: gg did push

      - name: Will the tests pass on Ubuntu too?
        run: gg can commit --force
